language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - 0.10
  - 0.12

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.12

install:
  - make install

script:
  - make test